Feature/common/add orm
alex-lairan/SimpleAuthJava pull request #11
Opened 2017-06-09 07:30 UTC by alex-lairan

Branche commune sur l'ajout de l'ORM (ActiveJDBC)[http://javalite.io/activejdbc]

2017-06-09 07:45 UTC, alex-lairan commented
J'ai fini le rebase :)

J'ai ajouter un main temporaire pour testé, il y a encore un soucis.
J'essaye de le résoudre à la pause.

2017-06-09 09:37 UTC, TristanEduProjet commented
ah t'as tout rebasé ?
ok je regarde

2017-06-09 13:16 UTC, TristanEduProjet requested changes
Quelques changements et questions

2017-06-09 13:16 UTC, TristanEduProjet commented on pom.xml
> +
détail, mais ligne vide à supprimer

2017-06-09 13:16 UTC, TristanEduProjet commented on pom.xml
> +        <activejdbc.version>1.4.13</activejdbc.version>
mettre la version avec les autres en dessous pour plus de visibilité

2017-06-09 13:16 UTC, TristanEduProjet commented on src/main/java/fr/esgi/simple_auth_java/User.java
> +    @NotNull @NonNull private String email;
remet le `@Email`, il sert à la validation du bean dans le test, mais n'a pas d'influence pour l'instant sur le runtime

2017-06-09 13:16 UTC, TristanEduProjet commented on src/main/java/Main.java
> +        User user = User.createIt(
Proposition, ce serait peu-être mieux qu'on déplace dans un(e) fichier/classe `Example` pour éviter le `main()` ?

2017-06-09 13:16 UTC, TristanEduProjet commented on pom.xml
> +        <dependency>
Comment t'as fait pour placer la moitié de la PR #9 en nouveau et pas le reste (pour le pom.xml) ? o.o

2017-06-10 07:04 UTC, alex-lairan commented on src/main/java/Main.java
> +        User user = User.createIt(
Quand je merge, je vais retirer tout simplement le commit, c'est pour ca que j'ai bien fait exprès de le mettre ailleurs ;)

2017-06-10 07:04 UTC, alex-lairan commented on src/main/java/fr/esgi/simple_auth_java/User.java
> +    @NotNull @NonNull private String email;
Ok

Mais ca ne fait pas doublon à validateEmailOf("email"); ?

2017-06-10 07:06 UTC, alex-lairan commented on pom.xml
> +        <dependency>
Je ne sais pas x)

2017-06-10 07:44 UTC, alex-lairan commented on pom.xml
> +        <activejdbc.version>1.4.13</activejdbc.version>
J'ai pas compris ^^

2019-03-06 15:42 UTC, closed without merging