Create Unit Test for SignUp.
alex-lairan/SimpleAuthJava pull request #16
Opened 2017-06-10 15:36 UTC by Maill

Unit Test => OK / Mock Test => Unable to do the test / Integ. Test => SignIn interface not fully implemented

2017-06-10 15:47 UTC, alex-lairan submitted a review, later dismissed

2017-06-10 15:47 UTC, alex-lairan commented on pom.xml
> +            <version>LATEST</version>
C'est pas préférable de figer la version?

2017-06-10 19:50 UTC, TristanEduProjet requested changes
un mock du User ?

2017-06-10 19:50 UTC, TristanEduProjet commented on pom.xml
> +            <version>LATEST</version>
Met la version en dur, LATEST n'est plus reconnu depuis Maven 3 (fonctionnalité retirée)
[Maven 3.x Compatibility Notes -- PluginMetaversionResolution](https://cwiki.apache.org/confluence/display/MAVEN/Maven+3.x+Compatibility+Notes#Maven3.xCompatibilityNotes-PluginMetaversionResolution)

2017-06-10 19:50 UTC, TristanEduProjet commented on pom.xml
> +            <version>LATEST</version>
d'ailleurs je suis étonné que Maven t'es pas renvoyé une erreur pour ça

2017-06-10 19:50 UTC, TristanEduProjet commented on src/test/java/fr/esgi/simple_auth_java/register/RegisterDBTest.java
> +        System.setIn(setIn);
faut que tu remette le input d'origine à la fin de ton test, car il est globale à *tout* le programme

2017-06-10 19:50 UTC, TristanEduProjet commented on src/test/java/fr/esgi/simple_auth_java/register/RegisterDBTest.java
> +        assertEquals(User.class, testUser.getClass());
à quoi ça sert ?
du moment que c'est un user (classe héritée ou non)

2017-06-10 19:50 UTC, TristanEduProjet commented on src/test/java/fr/esgi/simple_auth_java/register/RegisterDBTest.java
> +        assertEquals(new PasswordEncryptSHA256().encrypt(password), testUser.getPassword());
utilise l'`encryptor` du User, car rien ne dit que le User utilise toujours le SHA256

2017-06-11 09:44 UTC, olivierLefebvre96 commented on pom.xml
> +            <version>LATEST</version>
Je suis d'accord, on n'est jamais à l'abri de problèmes dû à un changement de version automatique.

2017-06-11 11:18 UTC, TristanEduProjet commented on pom.xml
> +            <version>LATEST</version>
j'ai répondu à votre question dans ma review

2017-06-11 11:31 UTC, Maill commented on src/test/java/fr/esgi/simple_auth_java/register/RegisterDBTest.java
> +        System.setIn(setIn);
C'est a dire ? J'ai pas compris.

2017-06-11 11:34 UTC, Maill commented on src/test/java/fr/esgi/simple_auth_java/register/RegisterDBTest.java
> +        assertEquals(User.class, testUser.getClass());
ça dérange tant que ça ? Je veux dire que au moment où je l'ai écrit je trouvais ça normal de tester la classe de l'objet (car on sait jamais ? ...). Après je suis d'accord que on est obligé d'avoir un "User".

2017-06-11 11:41 UTC, TristanEduProjet commented on src/test/java/fr/esgi/simple_auth_java/register/RegisterDBTest.java
> +        System.setIn(setIn);
bah à partir de cette ligne, `System.in` pointe sur `ByteArrayInputStream` même après la fin de ton test, car `System` est une variable globale de la JVM
donc tout le reste du programme va être affecté si tu ne remet pas l'input d'origine après ton test (qui pointe généralement sur la console)

2017-06-11 11:43 UTC, TristanEduProjet commented on src/test/java/fr/esgi/simple_auth_java/register/RegisterDBTest.java
> +        assertEquals(User.class, testUser.getClass());
Ce que je veut dire, c'est que là tu test si le user que tu as obtenu *est* un user et rien d'autre. Sauf que rien ne dit que la classe ne renverra pas un type hérité, qui ferra dans ce cas échoué ton test.
Le test est un peu inutile, vu que le type java fait que ce test est déjà fait à la compilation par Java.

2017-06-11 11:49 UTC, Maill commented on src/test/java/fr/esgi/simple_auth_java/register/RegisterDBTest.java
> +        System.setIn(setIn);
Ah ! Une fois les variables appelées, elle disparaissent du System.In, ça agit comme une Stack.

2017-06-11 11:53 UTC, TristanEduProjet commented on src/test/java/fr/esgi/simple_auth_java/register/RegisterDBTest.java
> +        System.setIn(setIn);
Je viens de vérifier dans la [javadoc](https://docs.oracle.com/javase/7/docs/api/java/lang/System.html), rien ne semble l'indiquer, car en plus `in` est une variable `static`.
Je ne suis pas convaincu, mais si tu me l'affirme

2017-06-11 12:10 UTC, Maill commented on src/test/java/fr/esgi/simple_auth_java/register/RegisterDBTest.java
> +        System.setIn(setIn);
Va faire le test en mode pas à pas. Justement, au début j'avais des problème car je mettait a la chaîne les infos avec System.setIn(), sachant qu'il n'enregistre que le dernier setIn à l'intérieur du System.In, et quand la fonction de création passait dans le System.In, la variable était récupéré puis supprimé. Ce qui m'a causé par la suite des NullPointerException.

2017-06-11 12:12 UTC, TristanEduProjet commented on src/test/java/fr/esgi/simple_auth_java/register/RegisterDBTest.java
> +        System.setIn(setIn);
ok

2017-06-11 17:16 UTC, alex-lairan commented
Rebase, t'a un soucis la ;)

2017-06-11 19:28 UTC, TristanEduProjet requested changes
2 petits changements

2017-06-11 19:28 UTC, TristanEduProjet commented on pom.xml
> +            <version>2.7.22</version>
Déplace la version des propriétés du pom (en haut) comme les autres.
d'ailleurs tu as encore `<mockito-all.version>...</mockito-all.version>` qui existe

2017-06-11 19:28 UTC, TristanEduProjet commented on pom.xml
> +            <version>3.16.1</version>
idem

2017-06-11 19:31 UTC, TristanEduProjet commented
il y a un problème avec la PR :
>*Maill* wants to merge 2 commits into `develop` from `signup/test`

2017-06-11 19:41 UTC, TristanEduProjet requested changes
presque

2017-06-11 19:41 UTC, TristanEduProjet commented on pom.xml
> -            <version>2.7.22</version>
perdu :)
tu dois mettre à la place `${mockito-core.version}` (référence à la propriété)

2017-06-11 19:41 UTC, TristanEduProjet commented on pom.xml
> -            <version>3.16.1</version>
perdu :)
tu dois mettre à la place `${mockito-core.version}` (référence à la propriété)

2017-06-11 19:41 UTC, TristanEduProjet commented on pom.xml
>              <scope>test</scope>
à retirer car on veut sqlite en runtime aussi (sinon dispo qu'en test)

2017-06-11 19:55 UTC, Maill commented on pom.xml
>              <scope>test</scope>
c'est a dire retirer ?

2017-06-11 20:02 UTC, TristanEduProjet commented on src/test/java/fr/esgi/simple_auth_java/register/RegisterDBTest.java
> +        assertEquals(User.class, testUser.getClass());
ça me gène toujours mais c'est pas grave :)

2017-06-11 20:02 UTC, TristanEduProjet approved these changes
c'est bon, je valide

2017-06-11 22:11 UTC, merged