Reset/test
alex-lairan/SimpleAuthJava pull request #19
Opened 2017-06-10 22:10 UTC by hyde777

I feel like i lack stuff on my test.
What are your thought?

2017-06-10 22:35 UTC, TristanEduProjet requested changes
beaucoup de changements

2017-06-10 22:35 UTC, TristanEduProjet commented on src/main/java/fr/esgi/simple_auth_java/reset/BadPasswordMatchException.java
> +public class BadPasswordMatchException extends RuntimeException {
c'est pour quoi cette classe ?

2017-06-10 22:35 UTC, TristanEduProjet commented on src/main/java/fr/esgi/simple_auth_java/reset/BadPasswordMatchException.java
> +public class BadPasswordMatchException extends RuntimeException {
regarde `IllegalResetException` ou `ResetException`

2017-06-10 22:35 UTC, TristanEduProjet commented on src/main/java/fr/esgi/simple_auth_java/reset/WeakPasswordException.java
> +public class WeakPasswordException extends RuntimeException {
idem que l'autre, pourquoi as-tu cette classe ?

2017-06-10 22:35 UTC, TristanEduProjet commented on src/main/java/fr/esgi/simple_auth_java/reset/WrongMailException.java
> +public class WrongMailException extends RuntimeException {
tu fais une vérification ?
c'est au User de s'en occuper

2017-06-10 22:35 UTC, TristanEduProjet commented on src/test/java/fr/esgi/simple_auth_java/reset/ResetTest.java
> +public class ResetTest {
le nom de la classe est incorrect
le nom doit être nomDeLaClasseTestée + Test

2017-06-10 22:35 UTC, TristanEduProjet commented on src/test/java/fr/esgi/simple_auth_java/reset/ResetTest.java
> +    Manager testManager = new Manager();
pourquoi le manager ?
tu test le Resetor qui n'a pas besoin du manager (interface externe)

2017-06-10 22:35 UTC, TristanEduProjet commented on src/test/java/fr/esgi/simple_auth_java/reset/ResetTest.java
> +    Resetor resetPasswordWithTempPwdByMail = mock(ResetorPasswordWithTempPwdByMail.class);
t'as fait l'inverse, c'est `ResetorPasswordWithTempPwdByMail` que tu dois tester, donc pas un mock

2017-06-10 22:35 UTC, TristanEduProjet commented on src/test/java/fr/esgi/simple_auth_java/reset/ResetTest.java
> +        testManager.reset(testUser, resetPasswordWithTempPwdByMail);
tu exécute le reset, mais où est-ce que tu teste que le reste s'est bien déroulé ?

2017-06-10 22:35 UTC, TristanEduProjet commented on src/test/java/fr/esgi/simple_auth_java/reset/ResetorPasswordByMailTest.java
> +            TimeUnit.MINUTES.sleep(30);
il n'y a pas de limite de temps dans les resetor

2017-06-10 22:35 UTC, TristanEduProjet commented on src/test/java/fr/esgi/simple_auth_java/reset/ResetorPasswordByMailTest.java
> +    Resetor resetPasswordByMail = mock(ResetorPasswordByMail.class);
idem

2017-06-10 22:35 UTC, TristanEduProjet commented on src/test/java/fr/esgi/simple_auth_java/reset/ResetorPasswordByMailTest.java
> +        testManager.reset(testUser, resetPasswordByMail);
idem

2017-06-10 22:35 UTC, TristanEduProjet commented on src/test/java/fr/esgi/simple_auth_java/reset/ResetorPasswordWithTokenTest.java
> +    Resetor resetPasswordWithToken = mock(ResetorPasswordWithOldPwd.class);
idem

2017-06-10 22:35 UTC, TristanEduProjet commented on src/test/java/fr/esgi/simple_auth_java/reset/ResetorPasswordWithTokenTest.java
> +        testManager.reset(testUser, resetPasswordWithToken);
n'échouera pas, et ou sont les input de test ?
parce que là sinon ton test va bloquer (le resetor attend l'input), et ça n’avancera plus

2017-06-10 22:35 UTC, TristanEduProjet commented on src/test/java/fr/esgi/simple_auth_java/reset/ResetorPasswordWithTokenTest.java
> +    Manager testManager = new Manager();
idem

2017-06-10 22:35 UTC, TristanEduProjet commented on src/test/java/fr/esgi/simple_auth_java/reset/ResetorPasswordWithOldPwdTest.java
> +        testManager.reset(testUser, resetPasswordByMail);
et les inputs ?

2017-06-10 22:35 UTC, TristanEduProjet commented on src/test/java/fr/esgi/simple_auth_java/reset/ResetorPasswordWithOldPwdTest.java
> +        testManager.reset(testUser, resetPasswordByMail);
idem

2017-06-10 22:35 UTC, TristanEduProjet commented on src/test/java/fr/esgi/simple_auth_java/reset/ResetorPasswordWithOldPwdTest.java
> +    Manager testManager = new Manager();
pas nécessaire

2017-06-10 22:35 UTC, TristanEduProjet commented on src/test/java/fr/esgi/simple_auth_java/reset/ResetorPasswordWithOldPwdTest.java
> +    Resetor resetPasswordByMail = mock(ResetorPasswordByMail.class);
idem

2017-06-11 09:49 UTC, hyde777 commented on src/test/java/fr/esgi/simple_auth_java/reset/ResetTest.java
> +public class ResetTest {
Je vais delete cette classe, oublié de la faire

2017-06-11 09:49 UTC, hyde777 commented on src/test/java/fr/esgi/simple_auth_java/reset/ResetTest.java
> +    Resetor resetPasswordWithTempPwdByMail = mock(ResetorPasswordWithTempPwdByMail.class);
Ok

2017-06-11 09:50 UTC, hyde777 commented on src/test/java/fr/esgi/simple_auth_java/reset/ResetTest.java
> +        testManager.reset(testUser, resetPasswordWithTempPwdByMail);
C sa ce que je comprenais pas, comment je sais que le reset s'est bien passer?

2017-06-11 09:53 UTC, hyde777 commented on src/main/java/fr/esgi/simple_auth_java/reset/BadPasswordMatchException.java
> +public class BadPasswordMatchException extends RuntimeException {
Le truc c'est que pour moi IllegalResetException et ResetException ne sont pas assez explicite

Je ne sais même pas dans quel cas elles se trigger

2017-06-11 09:53 UTC, hyde777 commented on src/main/java/fr/esgi/simple_auth_java/reset/WrongMailException.java
> +public class WrongMailException extends RuntimeException {
mhhh plutot au mailer non?

2017-06-11 09:55 UTC, TristanEduProjet commented on src/test/java/fr/esgi/simple_auth_java/reset/ResetTest.java
> +        testManager.reset(testUser, resetPasswordWithTempPwdByMail);
vu que le user est un mock, tu peux savoir s'il à était modifié par le resetor
tu test en plus que le nouveau mot de passe est bien celui que tu as voulu
(avec l'encryptor-disable)

2017-06-11 10:01 UTC, TristanEduProjet commented on src/main/java/fr/esgi/simple_auth_java/reset/BadPasswordMatchException.java
> +public class BadPasswordMatchException extends RuntimeException {
la javadoc n'est peut-être pas assez explicite
`IllegalResetException` survient si l'utilisateur à posé un problème lors du reset, et `ResetException` est pour englober toutes les autres exceptions qui aurait pu se produire (`IOException`, `SQLException`, `IndexOutOfBoundException`, etc)

2017-06-11 10:02 UTC, TristanEduProjet commented on src/main/java/fr/esgi/simple_auth_java/reset/WrongMailException.java
> +public class WrongMailException extends RuntimeException {
non, au user, car c'est une contrainte propre à lui
d'ailleurs c'est un point qui sera ajouter plus tard (elle est partiellement mise en place)

2017-06-11 10:05 UTC, hyde777 commented on src/main/java/fr/esgi/simple_auth_java/reset/BadPasswordMatchException.java
> +public class BadPasswordMatchException extends RuntimeException {
Bah c'est bizarre alors: on a aucun moyen de savoir si il y a eu des problème dans le reset autre que les problème générique?

Genre si le nouveau password est trop faible, comment est-ce qu'on le remonte? si on envoie un mail et qu'il ne répond jamais comment est-ce qu'on le sait? C'est ce genre d'exception qu'il nous manque.

2017-06-11 10:06 UTC, hyde777 commented on src/main/java/fr/esgi/simple_auth_java/reset/WrongMailException.java
> +public class WrongMailException extends RuntimeException {
Heu non non, je parle pas de si le mail est correcte, mais si l'envoie d'un message via le mail marche vraiment.(un ping?)

2017-06-11 10:07 UTC, hyde777 commented on src/test/java/fr/esgi/simple_auth_java/reset/ResetTest.java
> +        testManager.reset(testUser, resetPasswordWithTempPwdByMail);
heu on a pas juste besoin de tester si le nouveau mail est différent de l'ancien?

2017-06-11 10:08 UTC, hyde777 commented on src/test/java/fr/esgi/simple_auth_java/reset/ResetorPasswordWithTokenTest.java
> +        testManager.reset(testUser, resetPasswordWithToken);
Ha! il attend quel type d'input?

2017-06-11 10:11 UTC, TristanEduProjet commented on src/main/java/fr/esgi/simple_auth_java/reset/BadPasswordMatchException.java
> +public class BadPasswordMatchException extends RuntimeException {
le mot de passe trop faible est aussi tester qu'en test unitaire pour l'instant (on a pas eu le temps de faire toute la partie des contraintes)

2017-06-11 10:12 UTC, TristanEduProjet commented on src/main/java/fr/esgi/simple_auth_java/reset/BadPasswordMatchException.java
> +public class BadPasswordMatchException extends RuntimeException {
pour le mail, c'est obligatoire dans la procédure actuel du resetor, car il attend le retour de l'utilisateur, donc obliger qu'il réponde, sinon attente infinie
donc pas d'exception pour ca pour l'instant

2017-06-11 10:12 UTC, hyde777 commented on src/main/java/fr/esgi/simple_auth_java/reset/BadPasswordMatchException.java
> +public class BadPasswordMatchException extends RuntimeException {
ha! Dans ce cas c simple: si le mot de passe est trop simple tu envoie une exception custom ( en RuntimeException pas besoin de try catch)

2017-06-11 10:13 UTC, hyde777 commented on src/main/java/fr/esgi/simple_auth_java/reset/BadPasswordMatchException.java
> +public class BadPasswordMatchException extends RuntimeException {
Pas besoin de contrainte y'a juste besoin du cas pour

2017-06-11 10:13 UTC, TristanEduProjet commented on src/main/java/fr/esgi/simple_auth_java/reset/WrongMailException.java
> +public class WrongMailException extends RuntimeException {
j'ai utilisé une fonctionnalité spéciale de la lib pour rediriger en dev vers les log qui pointe sur la console
je t'ai laissé exprès une fonction pour modifier le mailer du resetor pour que tu puisse le remplacer par un mock et ainsi capturé le token ou mdp temporaire

2017-06-11 10:14 UTC, TristanEduProjet commented on src/test/java/fr/esgi/simple_auth_java/reset/ResetTest.java
> +        testManager.reset(testUser, resetPasswordWithTempPwdByMail);
bah non, vu que c'est le mdp qui est changé

2017-06-11 10:15 UTC, TristanEduProjet commented on src/test/java/fr/esgi/simple_auth_java/reset/ResetorPasswordWithTokenTest.java
> +        testManager.reset(testUser, resetPasswordWithToken);
`System.in`
regarde sur la branche de @Maill il à fait des choses sur ca

2017-06-11 10:17 UTC, hyde777 commented on src/main/java/fr/esgi/simple_auth_java/reset/WrongMailException.java
> +public class WrongMailException extends RuntimeException {
C'est quoi la fonction? (faudrais l'ajouter dans l'interface alors non?)

2017-06-11 10:18 UTC, TristanEduProjet commented on src/main/java/fr/esgi/simple_auth_java/reset/BadPasswordMatchException.java
> +public class BadPasswordMatchException extends RuntimeException {
non ne t'occupe pas de la force du mot de passe, oublie ça
c'est pas au resetor de s'en occuper, c'est au user ;)

2017-06-11 10:23 UTC, hyde777 commented on src/main/java/fr/esgi/simple_auth_java/reset/BadPasswordMatchException.java
> +public class BadPasswordMatchException extends RuntimeException {
Tu veux dire que si le nouveau mot de passe est trop faible c'est le User qui doit dire qu'il est trop faible? sa me semble pas logique: c'est le resetor qui fait l'action de reset le mdp, le mdp ne devrait même pas atteindre le User en cas de problème dans le Resetor.

2017-06-11 10:28 UTC, TristanEduProjet requested changes
problèmes de ton merge

2017-06-11 10:28 UTC, TristanEduProjet commented on src/main/java/fr/esgi/simple_auth_java/reset/ResetorPasswordWithOldPwd.java
> +public class ResetorPasswordWithOldPwd implements Resetor {
mauvais merge ...
`ForgetorPasswordWithTempPwdByMail` --> `ResetorPasswordByMail` --> `ResetorPasswordWithOldPwd` --> `ResetorPasswordWithTempPwdByMail` ??

2017-06-11 10:28 UTC, TristanEduProjet commented on src/main/java/fr/esgi/simple_auth_java/reset/ResetorPasswordByMail.java
> +public class ResetorPasswordByMail implements Resetor {
mauvais merge ...
`ForgetorPasswordWithTempPwdByMail` --> `ResetorPasswordByMail` --> `ResetorPasswordWithOldPwd` --> `ResetorPasswordWithTempPwdByMail` ??

2017-06-11 10:28 UTC, TristanEduProjet commented on src/main/java/fr/esgi/simple_auth_java/reset/ResetorPasswordWithTempPwdByMail.java
> +public class ResetorPasswordWithTempPwdByMail implements Resetor {
mauvais merge ...
`ForgetorPasswordWithTempPwdByMail` --> `ResetorPasswordByMail` --> `ResetorPasswordWithOldPwd` --> `ResetorPasswordWithTempPwdByMail` ??

2017-06-11 10:30 UTC, TristanEduProjet commented on src/main/java/fr/esgi/simple_auth_java/reset/BadPasswordMatchException.java
> +public class BadPasswordMatchException extends RuntimeException {
bah si c'est logique
mais bon on est à court de temps, alors t'en occupe pas, il n'y a pas cette vérification dans le projet pour l'instant

2017-06-11 10:31 UTC, TristanEduProjet commented on src/main/java/fr/esgi/simple_auth_java/reset/WrongMailException.java
> +public class WrongMailException extends RuntimeException {
non, car le mail est spécifique au resetor qu'il l'utilise, et bonne chance pour faire une interface générique pour (sans être exhaustif) Console + Mail + SMS + HTTP ...

2017-06-11 10:34 UTC, TristanEduProjet commented
pour les conflits suivants :
- src/main/java/fr/esgi/simple_auth_java/Manager.java
- src/main/java/fr/esgi/simple_auth_java/reset/ResetException.java
- src/main/java/fr/esgi/simple_auth_java/reset/Resetor.java
- src/main/java/fr/esgi/simple_auth_java/reset/ResetorPasswordByMail.java
- src/main/java/fr/esgi/simple_auth_java/reset/ResetorPasswordWithOldPwd.java

tu choisi "utiliser le leurs", la version de la common, ça évitera d'écraser la bonne version

2017-06-11 10:36 UTC, hyde777 commented on src/main/java/fr/esgi/simple_auth_java/reset/ResetorPasswordWithTempPwdByMail.java
> +public class ResetorPasswordWithTempPwdByMail implements Resetor {
Dude c'est le pb que je te parlais hier, Git est juste complètement perdu xD.

2017-06-11 10:38 UTC, TristanEduProjet commented on src/main/java/fr/esgi/simple_auth_java/reset/ResetorPasswordWithTempPwdByMail.java
> +public class ResetorPasswordWithTempPwdByMail implements Resetor {
bon je vais te résoudre ça (entorse à la règle)

2017-06-11 21:58 UTC, merged