Signup/dev
alex-lairan/SimpleAuthJava pull request #6
Opened 2017-06-04 17:09 UTC by olivierLefebvre96

ADDED:
- SQL connection feature
- SQL insertion feature
- User registration feature - first glimpse
- New Maven dependency of SQLite
- SQlite dataset and database

2017-06-04 17:51 UTC, TristanEduProjet requested changes
J'ai pas tout compris ...

2017-06-04 17:51 UTC, TristanEduProjet commented on pom.xml
> +        <!-- https://mvnrepository.com/artifact/org.xerial/sqlite-jdbc -->
ce commentaire ne sert à rien

2017-06-04 17:51 UTC, TristanEduProjet commented on src/main/java/fr/esgi/simple_auth_java/Manager.java
> +    public User signUp(@NonNull final Registor registor) throws IOException {
Créer un exception pour l'authentification (ex: `SignUpExcception`), qui pourra encapsuler une autre exception au besoin.

2017-06-04 17:51 UTC, TristanEduProjet commented on src/main/java/fr/esgi/simple_auth_java/operations/DBConnection.java
> +        String url = "jdbc:sqlite:C:\\Users\\Olivier\\IdeaProjects\\SimpleAuthJava\\src\\main\\resources\\database.db";
Utilise une URI relative et non absolue, car ca ne marchera que chez toi.

2017-06-04 17:51 UTC, TristanEduProjet commented on src/main/java/fr/esgi/simple_auth_java/operations/UserInsert.java
> +            connection.close();
utilise les try-with-ressource pour éviter les erreurs --> bonne pratique Java8

2017-06-04 17:51 UTC, TristanEduProjet commented on src/main/java/fr/esgi/simple_auth_java/register/Register.java
> +        BufferedReader br = new BufferedReader(new InputStreamReader(System.in));
Simple question : c'est pas mieux et plus simple avec un `Scanner` ?

2017-06-04 17:51 UTC, TristanEduProjet commented on src/main/java/fr/esgi/simple_auth_java/register/Registor.java
> +    User signUp() throws IOException;
_voir review dessus_

2017-06-04 17:51 UTC, TristanEduProjet commented on src/main/java/fr/esgi/simple_auth_java/register/Register.java
> +        return new User(email, firstname, lastname, password);
t'enregistre pas l'utilisateur dans la bdd ?

2017-06-04 17:51 UTC, TristanEduProjet commented on src/main/java/fr/esgi/simple_auth_java/operations/DBConnection.java
> +        String url = "jdbc:sqlite:C:\\Users\\Olivier\\IdeaProjects\\SimpleAuthJava\\src\\main\\resources\\database.db";
et retire la bdd binaire si tu la recréer dans le code (ajoute au gitignore)

2017-06-04 17:51 UTC, TristanEduProjet commented on src/main/java/fr/esgi/simple_auth_java/register/Register.java
> +public class Register extends DBConnection implements Registor{
pourquoi hérite de `DBConnection` ?

2017-06-04 17:51 UTC, TristanEduProjet commented on src/main/java/fr/esgi/simple_auth_java/operations/UserInsert.java
> +public class UserInsert extends DBConnection {
C'est quoi la différence avec `Register` ?

2017-06-04 17:51 UTC, TristanEduProjet commented on src/main/java/fr/esgi/simple_auth_java/register/Register.java
> +public class Register extends DBConnection implements Registor{
renomme-là `RegisterDB` pour éviter toute confusion

2017-06-04 18:06 UTC, olivierLefebvre96 commented on src/main/java/fr/esgi/simple_auth_java/register/Register.java
> +        return new User(email, firstname, lastname, password);
Si, via insert() dans UserInsert.

2017-06-04 18:06 UTC, olivierLefebvre96 commented on src/main/java/fr/esgi/simple_auth_java/register/Register.java
> +        BufferedReader br = new BufferedReader(new InputStreamReader(System.in));
Ça ne changera pas grand chose, non ?

2017-06-04 18:10 UTC, olivierLefebvre96 commented on src/main/java/fr/esgi/simple_auth_java/register/Register.java
> +public class Register extends DBConnection implements Registor{
Je me suis dit qu'il fallait qu'on "normalise" nos opérations sur la BDD, et j'ai voulu réfléchir jusqu'à assez loin pour prévoir ça.
La classe abstraite `DBConnection` ainsi que ses classes-filles, telles que `UserInsert`, serviraient à gérer nos opérations sur la BDD.
Ce n'est peut-être pas la meilleure solution. Un singleton pourrait faire l'affaire, mais il faudrait que je me penche là-dessus.

2017-06-04 18:11 UTC, olivierLefebvre96 commented on src/main/java/fr/esgi/simple_auth_java/operations/UserInsert.java
> +            connection.close();
Je vais voir ce que je peux faire.

2017-06-04 18:14 UTC, TristanEduProjet commented on src/main/java/fr/esgi/simple_auth_java/register/Register.java
> +        BufferedReader br = new BufferedReader(new InputStreamReader(System.in));
je ne pense pas

2017-06-04 18:14 UTC, olivierLefebvre96 commented on src/main/java/fr/esgi/simple_auth_java/operations/UserInsert.java
> +public class UserInsert extends DBConnection {
Je voulais séparer les opérations SQL des opérations non-SQL, mais je pense faire autrement.

2017-06-04 18:15 UTC, olivierLefebvre96 commented on src/main/java/fr/esgi/simple_auth_java/operations/DBConnection.java
> +        String url = "jdbc:sqlite:C:\\Users\\Olivier\\IdeaProjects\\SimpleAuthJava\\src\\main\\resources\\database.db";
Bien vu pour l'URI, j'avais oublié.
La BDD ne se créé pas via le code, mais il serait peut-être préférable qu'elle le soit.
Qu'en pensez-vous ?

2017-06-04 18:18 UTC, olivierLefebvre96 commented on src/main/java/fr/esgi/simple_auth_java/Manager.java
> +    public User signUp(@NonNull final Registor registor) throws IOException {
Ok

2017-06-04 18:47 UTC, alex-lairan commented on src/main/java/fr/esgi/simple_auth_java/operations/DBConnection.java
> +        String url = "jdbc:sqlite:C:\\Users\\Olivier\\IdeaProjects\\SimpleAuthJava\\src\\main\\resources\\database.db";
Je ne pense pas, c'est sensé être fait dans un Makefile ou autre truc.

En ruby, je fait `bundle exec rake db:create` je pense qu'il doit y avoir des outils similaires

2017-06-04 18:51 UTC, alex-lairan requested changes
Retrait de la DB binaire + Review commentaires :)

2017-06-04 18:51 UTC, alex-lairan commented on src/main/java/fr/esgi/simple_auth_java/operations/DBConnection.java
> +            System.out.println(e.getMessage());
Faudrais pas Exit le programme si la connexion DB fail?

2017-06-04 18:51 UTC, alex-lairan commented on src/main/java/fr/esgi/simple_auth_java/operations/UserInsert.java
> +            String sql = "INSERT INTO User (email, first_name, last_name, password, isConnected) " +
Y'a pas moyen d'utiliser un ORM, la c'est pas top je trouve :/
(j'aime pas le SQL :) )

2017-06-04 18:54 UTC, TristanEduProjet commented on src/main/java/fr/esgi/simple_auth_java/operations/DBConnection.java
> +        String url = "jdbc:sqlite:C:\\Users\\Olivier\\IdeaProjects\\SimpleAuthJava\\src\\main\\resources\\database.db";
en java c'est souvent une classe d'initialisation au démarrage qui s'en occupe, car pas de makefile pour les bdd (maven sait pas faire ca)

2017-06-04 19:02 UTC, TristanEduProjet commented on src/main/java/fr/esgi/simple_auth_java/operations/UserInsert.java
> +            String sql = "INSERT INTO User (email, first_name, last_name, password, isConnected) " +
c'est normal en java :)

2017-06-04 19:21 UTC, olivierLefebvre96 commented on src/main/java/fr/esgi/simple_auth_java/operations/UserInsert.java
> +            String sql = "INSERT INTO User (email, first_name, last_name, password, isConnected) " +
Après discussions : À ajouter plus tard.

2017-06-04 19:21 UTC, olivierLefebvre96 commented on src/main/java/fr/esgi/simple_auth_java/operations/DBConnection.java
> +            System.out.println(e.getMessage());
Fait.

2017-06-04 19:22 UTC, olivierLefebvre96 commented on src/main/java/fr/esgi/simple_auth_java/operations/DBConnection.java
> +        String url = "jdbc:sqlite:C:\\Users\\Olivier\\IdeaProjects\\SimpleAuthJava\\src\\main\\resources\\database.db";
À ajouter plus tard.

2017-06-04 19:22 UTC, olivierLefebvre96 commented on pom.xml
> +        <!-- https://mvnrepository.com/artifact/org.xerial/sqlite-jdbc -->
Effacé.

2017-06-08 11:54 UTC, alex-lairan approved these changes
Why not tant que l'on met l'ORM après :)

2017-06-08 11:54 UTC, alex-lairan commented on src/main/java/fr/esgi/simple_auth_java/register/RegisterDB.java
> +            String sql = "INSERT INTO User (email, first_name, last_name, password, isConnected) " +
Du coup on met l'ORM après?

2017-06-08 15:37 UTC, olivierLefebvre96 commented on src/main/java/fr/esgi/simple_auth_java/register/RegisterDB.java
> +            String sql = "INSERT INTO User (email, first_name, last_name, password, isConnected) " +
Oui, si on a le temps.

2017-06-08 15:48 UTC, TristanEduProjet requested changes
1 changement et 2 questions

2017-06-08 15:48 UTC, TristanEduProjet commented on src/main/java/fr/esgi/simple_auth_java/register/RegisterDB.java
> +        String password = null;
Ce serai pas mieux d'avoir un `User` à la place ?
Je sais pas dans qu'elle est le raisonnement derrière.

2017-06-08 15:48 UTC, TristanEduProjet commented on src/main/java/fr/esgi/simple_auth_java/register/RegisterDB.java
> +        try(BufferedReader br = new BufferedReader(new InputStreamReader(System.in))){
Le `BufferedReader` est inutile sur l'input d'une console et peu même te créer des décallages (le temps de remplir le buffer)

2017-06-08 15:48 UTC, TristanEduProjet commented on src/main/java/fr/esgi/simple_auth_java/register/RegisterDB.java
> +            connection.setAutoCommit(false);
pourquoi tu désactive l'auto-commit ?

2017-06-08 17:38 UTC, alex-lairan commented on src/main/java/fr/esgi/simple_auth_java/register/RegisterDB.java
> +        String password = null;
Ah bien vu, un User aurais bien sa place ! :)

2017-06-08 17:39 UTC, alex-lairan commented
Y'a de moins en moins de messages par commit, c'est bientot la fin de celui ci ! :)

2017-06-08 18:46 UTC, olivierLefebvre96 commented on src/main/java/fr/esgi/simple_auth_java/register/RegisterDB.java
> +            connection.setAutoCommit(false);
J'étais parti du principe que ça permettrait _peut-être_ une meilleure gestion des erreurs, plus tard. Mais il n'y en aura pas besoin ici, du coup.

2017-06-08 18:51 UTC, TristanEduProjet commented on src/main/java/fr/esgi/simple_auth_java/register/RegisterDB.java
> +            connection.setAutoCommit(false);
ok

2017-06-08 18:55 UTC, olivierLefebvre96 commented on src/main/java/fr/esgi/simple_auth_java/register/RegisterDB.java
> +        String password = null;
Si, mais la structure du constructeur de User ne permet pas d'instancier un User sans paramètres.

2017-06-08 18:55 UTC, olivierLefebvre96 commented on src/main/java/fr/esgi/simple_auth_java/register/RegisterDB.java
> +        try(BufferedReader br = new BufferedReader(new InputStreamReader(System.in))){
J'ai changé en mettant un Scanner.

2017-06-08 19:10 UTC, TristanEduProjet requested changes
Un changement ... ou pas ...
attend le retour sur le problème.

2017-06-08 19:10 UTC, TristanEduProjet commented on src/main/java/fr/esgi/simple_auth_java/register/RegisterDB.java
> +        return new User(email, firstname, lastname, password);
annule ce changement, car `User` ne crypte pas le mdp

2017-06-08 19:10 UTC, TristanEduProjet commented on src/main/java/fr/esgi/simple_auth_java/register/RegisterDB.java
> +        return new User(email, firstname, lastname, password);
ah erreur de prog, il (`User`) le crypte si initialiser avec un HashMap, je remote le bug.

2017-06-08 22:05 UTC, TristanEduProjet commented
@olivierLefebvre96 intègre les maj de develop (voir #9), et recorrige 98d9cff1c3e9c5570538c468bec7cdc80c1a43e8 .

2017-06-08 23:12 UTC, hyde777 commented
Il manque quoi pour valider la PR? on aurais dit qu'il y a du conflit?

2017-06-09 13:10 UTC, TristanEduProjet commented
@olivierLefebvre96 est en train d'intégrer la #9 et #13 pour corriger le User au niveau de 98d9cff1c3e9c5570538c468bec7cdc80c1a43e8 .

2017-06-09 15:41 UTC, TristanEduProjet commented
il faudrait trouvé une façon de ne pas mettre le cryptage en dur dans `RegisterDB`

2017-06-09 15:42 UTC, TristanEduProjet commented on pom.xml
> +        <!-- Test -->
tiens toi aussi ton intégration à remis des lignes qui n'ont pas changés en nouvelles ?

2017-06-09 15:42 UTC, TristanEduProjet approved these changes
ok pour moi

2017-06-09 15:47 UTC, merged